### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by qreeves** [shacknetisp/statsdb-interface#1]
``` text
sh-4.3$ ./server.py /home/qreeves/master/master/
[08/02/15 02:07:29] Caching...
Traceback (most recent call last):
  File "./server.py", line 136, in <module>
    server = Server()
  File "./server.py", line 70, in __init__
    self.tick()
  File "./server.py", line 88, in tick
    "SELECT id FROM games ORDER BY id DESC").fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
```

I have no idea what to do :stuck_out_tongue:

**Comment by shacknetisp** [comment]
I forgot to check if the database has data in it yet or not.
