### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by qreeves** [shacknetisp/statsdb-interface#6]
```
statsdb-interface/redeclipse/__init__.py", line 51, in __call__
    fcache["mode"][(gameid, mode)] = redeclipse(version).modes[mode]
AttributeError: 'NoneType' object has no attribute 'modes'
Traceback (most recent call last):
  File "./server.py", line 91, in <module>
    server = Server()
  File "./server.py", line 64, in __init__
    web.displays.displays['overview'].multi(None, self.db)
  File "statsdb-interface/web/displays/overview.py", line 18, in multi
    weapon = ws.single(name)
  File "statsdb-interface/dbselectors/__init__.py", line 123, in single
    cache[index] = (time.time(), self.make_single(specific))
  File "statsdb-interface/dbselectors/weapon.py", line 29, in make_single
    ret[t] = recentsum(t) or 0
  File "statsdb-interface/dbselectors/weapon.py", line 27, in <lambda>
    (specific,)).fetchone()[0]
  File "statsdb-interface/db.py", line 36, in execute
    return self.con.execute(*args)
sqlite3.OperationalError: user-defined function raised exception
```

**Comment by shacknetisp** [comment]
Fixed in b167a387ff723fb9a60a05c11d5b5c2ef36cc7b4
